### PR TITLE
Increasing filter method

### PR DESCRIPTION
**Pull request by neomarbassani**
Adding ability to user filter by client name and get cases where he's an Co-counsel

### CODE REVIEW

**Comment by aworley** [comment]
Hi Neomar,

Is there a typo on line 396?  The part that reads "FROM users loggedUser, cases LEFT JOIN contacts" doesn't look right.  Does that run on your system without a syntax error?  Please let me know what your thoughts are.

Aaron

**Comment by neomarbassani** [comment]
Hi Aaron,

It's right and running without errors on local environment and dev-centOS7.
I'm using it to get all cases, where user is Co-counsel.

**Comment by aworley** [comment]
OK, I see.  I was able to get it to run without error, great.  However,
when I ran it against a sample database, it does not return the user's open
case list.  Let me try to make the change.  It might make more sense, and
be more efficient, for me to make the change, since I was the one who
designed the database.

Aaron

**Comment by aworley** [comment]
Actually, I take that back.  I have it working now.  I'm going to merge
this in.

I think the case list returns does have a problem with it, but that problem
wasn't introduced by your code.  I'm going to follow up with Brian and Mark
on it.

One more thing, just a heads up that I'll need to adjust some of the
formatting to match our code style conventions here.

Thanks for putting this together.

Aaron

**Pull request merged**
